world_traveller/places/urls.py
from django.urls import path

from world_traveller.places.views import PlacesListView, PlaceDetailsView, \
    CommentPlaceView, like_place, EditPlaceView, DeletePlaceView, create_place

urlpatterns = [
    path('', PlacesListView.as_view(), name='list places'),
    path('details/<int:pk>', PlaceDetailsView.as_view(), name='place details'),
    path('like/<int:pk>', like_place, name='like place'),
    path('comment/<int:pk>', CommentPlaceView.as_view(), name='comment place'),
    path('create/', create_place, name='create place'),
    path('edit/<int:pk>', EditPlaceView.as_view(), name='edit place'),
    path('delete/<int:pk>', DeletePlaceView.as_view(), name='delete place'),


]

world_traveller/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('world_traveller.common.urls')),
    path('places/', include('world_traveller.places.urls')),
    path('auth/', include('world_traveller.world_traveller_auth.urls')),
    path('profiles/', include('world_traveller.profiles.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

world_traveller/places/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import CASCADE

from world_traveller.core.validators import validate_text_starts_with_capital

UserModel = get_user_model()


class Place(models.Model):
    """
    PlaceModel is created with custom and built-in
    fields validators. Foreign-key connection is
    created with the user that add the place.
    """
    name = models.CharField(
        max_length=50,
        validators=[validate_text_starts_with_capital],
    )

    location = models.CharField(
        max_length=50,
        validators=[validate_text_starts_with_capital],
    )

    description = models.TextField(
        validators=[validate_text_starts_with_capital],
    )
    image = models.ImageField(
        upload_to='places',
    )
    created_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )


class Comment(models.Model):
    """
    CommentModel is created with foreign-key connection
    to the place that it refers to. This is how users
    can comment each place and comments can be displayed.
    """
    text = models.TextField(
        max_length=200,
    )
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        UserModel,
        on_delete=CASCADE,
    )


class Like(models.Model):
    """
    LikeModel is created with foreign-key connection
    to the place that it refers to. This is how users
    can like each place and likes number can be displayed.
    """
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )


class Images(models.Model):
    """
    ImagesModel is created with foreign-key connection
    to the place that it refers to. This is how a user
    can add multiple images for one place.
    """
    place = models.ForeignKey(Place, on_delete=CASCADE)
    image = models.ImageField(
        upload_to='places',
        verbose_name='Image',
        blank=True,
        null=True,
    )

world_traveller/places/forms.py
from django import forms
from world_traveller.core.mixins import BootstrapFormMixin
from world_traveller.places.models import Place, Comment


class PlaceForm(BootstrapFormMixin, forms.ModelForm):
    class Meta:
        model = Place
        exclude = ('user',)


class CreatePlaceForm(PlaceForm):
    pass


class EditPlaceForm(PlaceForm):
    class Meta:
        model = Place
        exclude = ('user',)
        widgets = {
            'name': forms.TextInput(
                # To disable Name Field when edit a place.
                attrs={
                    'readonly': 'readonly',
                }
            )
        }


class CommentForm(forms.ModelForm):
    """
    CommentForm is created and TextField is modified
    by widgets attrs to change its size when displayed.
    """
    place_pk = forms.IntegerField(
        widget=forms.HiddenInput()
    )

    class Meta:
        model = Comment
        fields = ('text', 'place_pk')

        widgets = {
            'text': forms.Textarea(
                attrs={
                    'style': 'height: 60px; width: 1050px;',
                }
            )
        }

    def save(self, commit=True):
        place_pk = self.cleaned_data['place_pk']
        place = Place.objects.get(pk=place_pk)
        comment = Comment(
            text=self.cleaned_data['text'],
            place=place,
        )
        if commit:
            comment.save()
        return comment

world_traveller/places/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from world_traveller.core.views import PostOnlyView
from world_traveller.places.forms import EditPlaceForm, CreatePlaceForm, CommentForm
from world_traveller.places.models import Place, Images, Like, Comment

UserModel = get_user_model()


class PlacesListView(ListView):
    """Class-based view that show places list is created."""
    model = Place
    template_name = 'places/places_list.html'
    context_object_name = 'places'
    ordering = ['-created_on']


@login_required(login_url='/auth/sign_in/')
def create_place(request):
    """
    Function-based view to add new place is created.
    ImageFormset is used to upload multiple images
    with only one ImageField when create a new place.
    Only logged in users can create a place.
    """

    ImageFormset = modelformset_factory(Images, fields=('image',), extra=3)
    if request.method == 'POST':
        form = CreatePlaceForm(request.POST, request.FILES)
        formset = ImageFormset(request.POST, request.FILES)

        # Validation of form and formset
        if form.is_valid() and formset.is_valid():
            place = form.save(commit=False)
            place.user = request.user
            place.save()

            # Saving each image from the formset
            for f in formset:
                try:
                    photo = Images(place=place, image=f.cleaned_data['image'])
                    photo.save()
                except Exception:
                    break

            return redirect('list places')
    else:
        form = CreatePlaceForm()
        formset = ImageFormset(queryset=Images.objects.none())

    context = {
        'form': form,
        'formset': formset,
    }

    return render(request, 'places/place_create.html', context)


class EditPlaceView(LoginRequiredMixin, UpdateView):
    """
    Class-based view to edit an existing place.
    It can be edited only by the user that created it
    and only when the user is signed in.
    Only logged in users can edit a place.
    """
    model = Place
    context_object_name = 'place'
    template_name = 'places/place_edit.html'
    form_class = EditPlaceForm
    success_url = reverse_lazy('profile details')


class DeletePlaceView(LoginRequiredMixin, DeleteView):
    """
    Class-based view to delete an existing place.
    It can be deleted only by the user that created it
    and only when the user is signed in.
    Only logged in users can delete a place.
    """
    template_name = 'places/place_delete.html'
    model = Place
    success_url = reverse_lazy('profile details')


class PlaceDetailsView(DetailView):
    """
    Class-based view to show place details. It displays
    place images, comments and likes for everyone and
    Edit/Delete button only for the user that created it.
    All users can see places' details.
    """
    model = Place
    template_name = 'places/place_details.html'
    context_object_name = 'place'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        place = context['place']
        place.likes_count = place.like_set.count()
        is_owner = place.user == self.request.user

        is_liked_by_user = place.like_set.filter(user_id=self.request.user.id) \
            .exists()

        context['comment_form'] = CommentForm(
            initial={
                'place_pk': self.object.id,
            }
        )
        context['comments'] = place.comment_set.all().order_by('-created_on')
        context['is_owner'] = is_owner
        context['is_liked'] = is_liked_by_user

        return context


class CommentPlaceView(LoginRequiredMixin, PostOnlyView):
    """
    Class-based view to show places' comments. It displays
    comments, the users that created them and they are
    being displayed by the time of the last added one.
    Only logged in users can comment a place.
    """
    form_class = CommentForm

    def form_valid(self, form):
        place = Place.objects.get(pk=self.kwargs['pk'])
        comment = Comment(
            text=form.cleaned_data['text'],
            place=place,
            user=self.request.user,
        )
        comment.save()

        return redirect('place details', place.id)

    def form_invalid(self, form):
        pass


@login_required(login_url='/auth/sign_in/')
def like_place(request, pk):
    """
    Function-based view to show places' likes. It displays
    the number of likes. A place cannot be liked by the user
    that created it. Only logged in users can like a place.
    """
    place = Place.objects.get(pk=pk)
    like_object_by_user = place.like_set.filter(user_id=request.user.id)

    if like_object_by_user.exists():
        like_object_by_user.delete()
    else:
        like = Like(
            place=place,
            user_id=request.user.id,
        )
        like.save()

    return redirect('place details', place.id)


# class CreatePlaceView(LoginRequiredMixin, CreateView):
#     model = Place
#     form_class = CreatePlaceForm
#     success_url = reverse_lazy('list places')
#     template_name = 'places/place_create.html'
#
#     def form_valid(self, form):
#         place = form.save(commit=False)
#         place.user = self.request.user
#         place.save()
#         return super().form_valid(form)
#
#     def form_invalid(self, form):
#         return self.render_to_response(
#             self.get_context_data(request=self.request, form=form))
#
#     def get_context_data(self, **kwargs):
#         context = super(CreatePlaceView, self).get_context_data(**kwargs)
#         return context

templates/places/place_create.html
{% extends 'common/base.html' %}
{% block content %}

    <div class="slider">
        <div class="Modern-Slider content-section" id="top">
            <div class="item item-2">
                <div class="img-fill">
                    <div class="image"></div>
                    <div class="info">
                        <div class="container">
                            <h1 class="text-center">Add New Place</h1>
                            <div class="row">
                                <div class="col-lg-3"></div>
                                <div class="col-lg-6" style="color: #f9f9f9; text-align: left">
                                    <form method="post" class="furniture-form" action="{% url 'create place' %}"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form }}
                                        {{ formset.as_table }}
                                        <br>
                                        <button class="btn" style="color: #45489a; width: 70px" type="submit">Add
                                        </button>
                                    </form>
                                </div>
                                <div class="col-lg-3"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/places/place_delete.html
{% extends 'common/base.html' %}
{% block content %}

    <div class="slider">
        <div class="Modern-Slider content-section" id="top">
            <div class="item item-3">
                <div class="img-fill">
                    <div class="image"></div>
                    <div class="info">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-12 text-center">
                                    <h1>Are you sure you want to delete {{ place.name }}?</h1>
                                    <div class="m-auto d-flex justify-content-center">
                                        <div class="m-2">
                                            <form method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <input type="submit" value="Confirm" class="btn btn-danger"
                                                       style="width: 100px"/>
                                            </form>
                                            <br>
                                        </div>
                                        <div class="m-2">
                                            <a class="btn"
                                               style="background-color: #45489a; color: #f9f9f9; width: 100px;"
                                               href="javascript:history.back()">No, go back</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/places/place_details.html
{% extends 'common/base.html' %}
{% block content %}

    <div class="page-content">
        <section id="featured" class="content-section">
            <div class="section-heading">
                <h1>{{ place.name }}<br><em>{{ place.location }}</em></h1>
                <p>{{ place.description }}</p>
            </div>

            <div class="section-content">
                <div class="owl-carousel owl-theme">
                    <div class="item" style="background-color: #dbdbdb;">
                        <div class="image" style="width: auto; height: 450px;">
                            <a href="{{ place.image.url }}" data-lightbox="image"><img src="{{ place.image.url }}" style="width: 100%; height: 100%; object-fit: contain"></a>
                            {#                            <img src="{{ place.image.url }}" alt="" style="height: 430px">#}
                        </div>
                        <div class="text-content">
                            <div>
                                {% if is_owner %}
                                    <a href="{% url 'edit place' place.id %}" class="btn"
                                       style="background-color: #45489a; color: #f9f9f9; width: 70px;">Edit</a>
                                    <a href="{% url 'delete place' place.id %}" class="btn btn-danger">Delete</a>
                                {% else %}
                                    <a href="{% url 'like place' place.id %}">
                                        {% if is_liked %}
                                            <i class="fa fa-heart" aria-hidden="true"></i>
                                        {% else %}
                                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                                        {% endif %}
                                    </a>
                                {% endif %}
                                <p class="mt-2" style="font-size: larger">Likes: {{ place.likes_count }}</p>
                            </div>
                        </div>
                    </div>
                    {% for p in place.images_set.all %}
                        <div class="item" style="background-color: #dbdbdb;">
                            <div class="image" style="width: auto; height: 450px;">
                                    <a href="{{ p.image.url }}" data-lightbox="image"><img src="{{ p.image.url }}" style="width: 100%; height: 100%; object-fit: contain"></a>
                            </div>
                        </div>
                 {% endfor %}
                </div>
            </div>

        </section>

        <h4 style="text-align: center">Comments</h4>
        <div class="d-block" style="background-color: #dbdbdb; padding: 1px; width: 71%; position: absolute; left: 26%">

            {% if comments %}
                {% for comment in comments %}
                    <div class="box" style="text-align: center">
                        <h5><em><u>{{ comment.user }}:</u> {{ comment.text }} {{ comment.created_on }}</em></h5>
                        <hr>
                    </div>
                {% endfor %}
            {% else %}
                <div class="box" style="text-align: center">
                    <br>
                    <h4>There are no comments for this place.</h4>
                    <br>
                </div>
            {% endif %}
            <div class="box" style="text-align: center">
                {% if not is_owner %}
                    <form method="post" action="{% url 'comment place' place.id %}">
                        {% csrf_token %}
                        {{ comment_form }}
                        <button class="btn" style="background-color: #45489a; color: #f9f9f9; width: 120px;"
                                type="submit">Add comment
                        </button>
                        <br><br><br>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/places/place_edit.html
{% extends 'common/base.html' %}
{% block content %}

    <div class="slider">
        <div class="Modern-Slider content-section" id="top">
            <div class="item item-2">
                <div class="img-fill">
                    <div class="image"></div>
                    <div class="info">
                        <div class="container">
                            <h1 class="text-center">Edit Place</h1>
                            <div class="row">
                                <div class="col-lg-3"></div>
                                <div class="col-lg-6" style="color: #f9f9f9; text-align: left">
                                    <form method="post" class="furniture-form" action="{% url 'edit place' place.id %}"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form }}
                                        <br>
                                        <button class="btn" style="color: #45489a; width: 70px" type="submit">Edit
                                        </button>
                                    </form>
                                </div>
                                <div class="col-lg-3"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/places/places_list.html
{% extends 'common/base.html' %}
{% load profile_complete_notification %}

{% block content %}

    <div class="page-content">
        <section id="featured" class="content-section">
            <div class="section-heading">
                <h1>Featured<br><em>Places</em></h1>
                {% if places %}
                    <p>View people's most enjoyable places around the world,
                        <br>share your favourite ones and inspire the others to travel.</p>
                {% else %}
                    <p>There are still no published destinations.
                        <br>Be the first one to add your favourite place <a href="{% url 'create place' %}">HERE</a></p>
                {% endif %}
            </div>
            <p>{% profile_complete_notification %}</p>

            <div class="section-content">
                <div class="owl-carousel owl-theme">
                    {% for place in places %}
                        <div class="item" style="background-color: #dbdbdb;">
                            <div class="image" style="width: auto; height: 450px; ">
                                <img src="{{ place.image.url }}" alt="" style="width: 100%; height: 100%; object-fit: contain">
                                <div class="featured-button button">
                                    <a href="{% url 'place details' place.id %}">View More Photos</a>
                                </div>
                            </div>
                            <div class="text-content">
                                <h4>{{ place.name }}</h4>
                                <span>{{ place.location }}</span>
                                <p>{{ place.description }}</p>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </section>
    </div>

{% endblock %}